name: New Issue/PR Auto Triage
on: [issues, pull_request]
jobs:
  Triage:
    runs-on: ubuntu-latest
    steps:
    - name: add-new-issues-to-organization-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: github.event_name == 'issues' && github.event.action == 'opened'
      env:
        GITHUB_TOKEN: ${{ secrets.EXORIUM_SECRET }}
        GITHUB_PROJECT_URL: https://github.com/orgs/flitzstudios/projects/1
        GITHUB_PROJECT_COLUMN_NAME: Awaiting triage
