name: Triage Labelled Issues
on:
  issues:
    types: [labeled]
jobs:
  Triage:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.EXORIUM_SECRET }}"
        project-url: "https://github.com/orgs/flitzstudios/projects/1"
        column-name: "Delayed"
        label-name: "delayed"
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.EXORIUM_SECRET }}"
        project-url: "https://github.com/orgs/flitzstudios/projects/1"
        column-name: "Low priority"
        label-name: "low priority"
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.EXORIUM_SECRET }}"
        project-url: "https://github.com/orgs/flitzstudios/projects/1"
        column-name: "Medium priority"
        label-name: "medium priority"
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.EXORIUM_SECRET }}"
        project-url: "https://github.com/orgs/flitzstudios/projects/1"
        column-name: "High priority"
        label-name: "high priority"
